Add a mechanism for generating an RC script that can be used on UNIX systems to configure the server to automatically start when the system boots.
Also, update the stop-ds script so that if the server is to be stopped via kill
but no PID file is present, the stop script will generate an error instead of
trying to invoke the stop task (which is guaranteed to fail since the attempt
will be made anonymously, and this will give a confusing error message).

OpenDS Issue Number:  526

diff --git a/opends/resource/bin/stop-ds b/opends/resource/bin/stop-ds
--- a/opends/resource/bin/stop-ds
+++ b/opends/resource/bin/stop-ds
@@ -189,6 +189,10 @@ then
         STOPPED=0
       fi
     fi
+  else
+    echo "ERROR:  Unable to find the server.pid file to determine the process"
+    echo "        ID of the OpenDS process to terminate."
+    exit 1
   fi
 fi
 
