Fix for issue 1273 (exception if JAVA_HOME undefined in scripts).
The fix consists of modifying the scripts to launch the InstallDS classwith a test option using the JVM
 that was found.  If the JVM can be successfully launched, the JVM is compatible with 1.5, if not we as
sume that is not compatible with JDK 1.5.

The downside of the fix is that it requires an additional start of the JVM each time the command line i
s launched. That is why the fix only applies to setup, uninstall, upgrade, start and stop command lines.  The modifications in _server-script.* and _client-script.sh just modify the message displayed when a JVM could not be found (informing that JDK 1.5 or later can be used).

diff --git a/opendj-sdk/opends/resource/bin/stop-ds b/opendj-sdk/opends/resource/bin/stop-ds
--- a/opendj-sdk/opends/resource/bin/stop-ds
+++ b/opendj-sdk/opends/resource/bin/stop-ds
@@ -104,6 +104,25 @@ export CLASSPATH
 SCRIPT_NAME_ARG="-Dorg.opends.server.scriptName=stop-ds"
 export SCRIPT_NAME_ARG
 
+# Test that the provided JDK is 1.5 compatible.
+if test -z "${JAVA_ARGS}"
+then
+  "${JAVA_BIN}" org.opends.server.tools.InstallDS -t 2> /dev/null
+  if test ${?} -ne 0
+  then
+    echo "ERROR:  The detected Java version could not be used.  Please set "
+    echo "        JAVA_HOME to the root of a Java 5.0 installation."
+    exit 1
+  fi
+else
+  "${JAVA_BIN}" ${JAVA_ARGS} org.opends.server.tools.InstallDS -t 2> /dev/null
+  if test ${?} -ne 0
+  then
+    echo "ERROR:  The detected Java version could not be used with the specified"
+    echo "Java arguments.  Please set  JAVA_HOME to the root of a Java 5.0 installation."
+    exit 1
+  fi
+fi
 
 "${JAVA_BIN}" ${JAVA_ARGS} ${SCRIPT_NAME_ARG} \
   org.opends.server.tools.StopDS --checkStoppability "${@}"
